### ISSUE TITLE
Allow Locales to be set in an environment and allow fallback code to be removed

### ISSUE THREAD

**Issue by Engerim** [labd/contentful-go#39]
* atm the fallback code can not be removed, as contentful expects to send `fallbackCode = null` in the json
* also it is not possible atm to create a locale in an enviroment

I would be happy to create a pr for this as we need this and have it already in a fork. Just want to know upfront if this feature is something you want to have in repo

**Comment by demeyerthom** [comment]
Hi @Engerim ,

Apologies for the late reply. A PR would be great! We are not currently using or maintaining this provider (that might change in the future if we get a new project using contentful), so any changes and updates from your end are welcome!
